app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import db
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'users',lazy = "dynamic")
    comment = db.relationship('Comment',backref = 'users',lazy = "dynamic")

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    def __repr__(self):
        return f'User {self.username}'
class Blog(db.Model):
    __tablename__='blogs'
    id=db.Column(db.Integer,primary_key=True)
    title=db.Column(db.String(255))
    blog=db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))




class Comment(db.Model):
    __tablename__='comments'
    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(255))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,BooleanField,SubmitField,TextAreaField,SelectField
from wtforms.validators import Required,Email,EqualTo
from wtforms import ValidationError
from ..models import Blog,Comment

class BlogForm(FlaskForm):
    title=SelectField('title',
        choices=[('sports', 'sports'), ('life style', 'life style'), ('tech', 'tech'), ('funny', 'funny')], validators = [Required()])
    blog = TextAreaField('pitblogch',validators=[Required()])
    submit = SubmitField('submit')
class CommentForm(FlaskForm):
    comment=TextAreaField('comment',validators=[Required()])
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap=Bootstrap()
db = SQLAlchemy()
def create_app(config_name):
    app= Flask(__name__)

    app.config.from_object(config_options[config_name])
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint (auth_blueprint , url_prefix='/auth')
    # app.config['SECRET_KEY'] ='1234'
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)




    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template, url_for,redirect
from . forms import BlogForm,CommentForm
from ..models import Blog,Comment
from . import main
from .. import db




@main.route('/')
def index():
    blogs=Blog.query.all()
    return render_template('index.html', blogs=blogs)
@main.route('/logb',methods=['GET','POST'])
def blog():
    blog_form=BlogForm()
    if blog_form.validate_on_submit():
        blog=Blog(title=blog_form.title.data,blog=blog_form.blog.data)
        db.session.add(blog)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('blog.html',blog_form=blog_form)
@main.route('/comment',methods=['GET','POST'])

def comment():

    comment_form=CommentForm()
    if comment_form.validate_on_submit():
        comment=Comment(comment=comment_form.comment.data)
        db.session.add(comment)
        db.session.commit()
        # return redirect(url_for('main.index'))

    comments=Comment.query.all()
    return render_template('comment.html',comment_form=comment_form,comments=comments)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  -->


{% block navbar %}

    {% include 'navbar.html' %}
{% endblock %}

app/templates/blog.html
{%extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
{{wtf.quick_form(blog_form)}}
{% endblock %}
</div>

app/templates/comment.html
{%extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
<div class="container">
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
        <h1>Submit Comment Here.</h1>
      <!-- Login form -->
      {{wtf.quick_form(comment_form)}}

     </div>
     <div clas="col-md-2"> </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h1>Comments</h1>
        {%for comment in comments%}
        <p>{{comment.comment}}</p>
        {%endfor%}
      </div>

    </div>
</div>
{% endblock %}

app/templates/index.html
{%extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
{% endblock %}
{%block content%}
<body class='body'>
  {%for blog in blogs%}

  <div class="col-md-4 jumbotron">
  <h1 class="title">{{blog.title}}</h1>
    <p>{{blog.blog}}</p>
    <button><a href="{{url_for('main.comment')}}">comment</a></button><button><i class="fa fa-thumbs-up"></i></button><button><i class="fa fa-thumbs-down"></i></button>
    </div>

    {%endfor%}

</body>
<style>
.body{
  background-image: url('https://png.pngtree.com/thumb_back/fw800/back_pic/03/86/57/8357cfa9a9ab9c4.jpg');
  background-repeat: no-repeat;
  background-size: cover;
}
.title{
  text-align: center;
}
.jumbotron{
  background-color: bisque;
  color: black;
  margin-right: 50px;
}
</style>
{%endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
       <div class="container-fluid">
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="/">Blogapp </a>
           </div>
           <div class="navbar-collapse collapse">
               <ul class="nav navbar-nav">
                   <li><a href="/">Home</a></li>
               </ul>
                  <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('main.blog')}}">create a blog</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
                </ul>

           </div>

       </div>
   </div>
<style>
.navbar-inverse{
  background-color:bisque ;

  border-style: none;
}

</style>